config/routes.rb
Rails.application.routes.draw do
  root              to: 'find_the_dog#landing'

  get 'questions',  to: 'find_the_dog#questions'
  get 'about',  	to: 'find_the_dog#about'
  post 'result',    to: 'find_the_dog#doing'
  get 'result',     to: 'find_the_dog#result'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dog.rb
class Dog < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/find_the_dog_controller.rb
class FindTheDogController < ApplicationController
  def landing
  end

  def about
  end

  def questions
  end

  def doing
    @dogs = Dog.all
    @you = [
      params[:sociable].to_i - params[:independent].to_i,
      params[:intelligent].to_i - params[:straightforward].to_i,
      params[:energetic].to_i - params[:quiet].to_i,
      params[:brave].to_i - params[:cautious].to_i,
      params[:gentle].to_i - params[:active].to_i,
      params[:patient].to_i - params[:stubborn].to_i
    ]

    @result = ""
    @smallest_sum = 24
    @dogs.each do |dog|
      @sum = 0
      @sum += (dog.char0 - @you[0]).abs
      @sum += (dog.char1 - @you[1]).abs
      @sum += (dog.char2 - @you[2]).abs
      @sum += (dog.char3 - @you[3]).abs
      @sum += (dog.char4 - @you[4]).abs
      @sum += (dog.char5 - @you[5]).abs

      if @sum < @smallest_sum
        @result = dog
        @smallest_sum = @sum
      end
    end
    redirect_to action: "result", id: @result.id
  end

  def result
    @result = Dog.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/find_the_dog_helper.rb
module FindTheDogHelper
end

app/views/find_the_dog/about.html.erb
<main>
	<section class="about-page">
		<div class="container ">
			<div class="row">
				<div class="col-xs-12">
					<h2 class="about-title">Project /Binoo/</h2>
				</div>
			</div>
			<div class="row">
				<div class="col-sm-10">
					<p class="about-description">
						Hello World! We are a Seoul-based &amp; Pittsburgh-based web developer. Enjoying hands-on experience and pushing the boundaries together, We love to ideate, design and develop something new outside the box as a <span class="result-link">thinker and doer</span>. Please feel free to reach out to us anytime if you wanna be our friend and chat with us :) </p>
				</div>
			</div>
			<div class="row">
				<div class="about-profile col-sm-3 col-sm-offset-2">
					<div class="about-img m-auto center-block"><%= image_tag 'js.jpg', class: "img-responsive center-block", alt: "jisup" %></div>
					<div class="profile-text text-center">
						<p class="profile-role">Backend</p>
						<h2 class="profile-name">Jeesub <span class="profile-detail">@Seoul</span></h2>
						<div class="link">
							<a class="link-item" target="_blank" href="https://www.linkedin.com/in/jeesub/" aria-label="Go to LinkedIn Page">
								<i class="fa fa-linkedin"></i>
							</a>
							<a class="link-item" target="_blank" href="https://github.com/jeesub" aria-label="Go to Github Page">
								<i class="fa fa-github"></i>
							</a>
							<a class="link-item" target="_blank" href="mailto:blindschokolade@gmail.com" aria-label="Send an Email">
								<i class="fa fa-envelope"></i>
							</a>
						</div>
					</div>
				</div>

				<div class="about-profile col-sm-3 col-sm-offset-2">
					<div class="about-img m-auto center-block"><%= image_tag 'sw.jpg', class: "img-responsive center-block", alt: "sunwoo" %></div>
					<div class="profile-text text-center">
						<p class="profile-role">Frontend</p>
						<h2 class="profile-name">Sunwoo <span class="profile-detail">@Pittsburgh</span></h2>

						<div class="link">
							<a class="link-item" target="_blank" href="https://www.linkedin.com/in/sunny-sunwoo-park/" aria-label="Go to LinkedIn Page">
								<i class="fa fa-linkedin"></i>
							</a>
							<a class="link-item" target="_blank" href="https://github.com/sunny-sunwoo" aria-label="Go to Github Page">
								<i class="fa fa-github"></i>
							</a>
							<a class="link-item" target="_blank" href="mailto:seonwoo1@andrew.cmu.edu" aria-label="Send an Email">
								<i class="fa fa-envelope"></i>
							</a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
</main>
<footer>
	<div class="container">
		<div class="row">
			<div class="col-sm-2">
				<%= link_to "HOME", root_path, class: "result-link" %>
			</div>
			<div class="col-sm-2 col-sm-offset-8 text-right">
				<%= link_to "May.2018", root_path, class: "result-link" %>
			</div>
		</div>
	</div>
</footer>

app/views/find_the_dog/landing.html.erb
<% provide(:title, "Binoo - Find Your Doggie") %>
<% provide(:description, 'A simple personality test to see who you are in the lovely doggie world. Now, take a breath and meet your new best friend!') %>
<% provide(:image, request.base_url + asset_path('landing-logo.jpg')) %>
<main>
	<section class="landing-page">
		<div class="container">
			<div class="row text-center flex-container">
				<div class="col-lg-6 col-md-10">
					<%= image_tag 'landing-logo.jpg', class: "landing-img img-responsive center-block", alt: "logo" %>
					<h2 class="landing-title">Find Your Doggie </h2>
					<p class="landing-description center-block"> Hello there! Here is a simple personality test to see who you are in the lovely doggie world. Now, take a breath and meet your new best friend! &#x1F436;</p>
					<%= link_to "start", questions_path, class:"btn__start" %>
				</div>
			</div>
		</div>
	</section>
</main>
<footer>
	<div class="container">
		<div class="row">
			<div class="col-sm-2">
				<%= link_to "Proj.Binoo", about_path, class:"result-link" %>
			</div>
			<div class="col-sm-2 col-sm-offset-8 text-right">
				<%= link_to "May.2018", root_path, class: "result-link" %>
			</div>
		</div>
	</div>
</footer>

app/views/find_the_dog/questions.html.erb
<% provide(:title, "question | Binoo") %>
<% provide(:description, 'question to Find Your Doggie') %>
<% provide(:image, request.base_url + asset_path('landing-logo.jpg')) %>
<main class="container">
	<section class="questions-page row text-center">
		<%= form_tag(result_path, method: :post) do %>

		  <div class="each-question ">
		  	<div class="question-content">I've got more than 50 likes for any post at Facebook.</div>
		  	<span class="label-no">NO</span>
		  	<label for="sociable_-1" id="sociable-label-1" class="check-no" onclick="checkNo(id)">
		  		<%= radio_button_tag(:sociable, "-1", false, required: 'required') %>
		  	</label>
		  	<label for="sociable_0" id="sociable-label-2" class="check-maybe" onclick="checkMaybe(id)">
		  		<%= radio_button_tag(:sociable, "0") %>
		  	</label>
		  	<label for="sociable_1"  id="sociable-label-3" class="check-yes" onclick="checkYes(id)">
		  		<%= radio_button_tag(:sociable, "1") %>
		  	</label>
		  	<span class="label-yes">YES</span>
		  </div>


		  <div class="each-question">
		  	<div class="question-content">I remember what I ate for lunch yesterday.</div>
		  	<span class="label-no">NO</span>
		  	<label for="intelligent_-1" id="intelligent-label-1" class="check-no" onclick="checkNo(id)">
		  		<%= radio_button_tag(:intelligent, "-1", false, required: 'required') %>
		  	</label>
		  	<label for="intelligent_0" id="intelligent-label-2"  class="check-maybe" onclick="checkMaybe(id)">
		  		<%= radio_button_tag(:intelligent, "0") %>
		  	</label>
		  	<label for="intelligent_1" id="intelligent-label-3" class="check-yes" onclick="checkYes(id)">
		  		<%= radio_button_tag(:intelligent, "1") %>
		  	</label><span class="label-yes">YES</span>
		  </div>


		  <div class="each-question">
		  	<div class="question-content">I have broken my bones while I was playing.</div>
		  	<span class="label-no">NO</span>
		  	<label for="energetic_-1" id="energetic-label-1" class="check-no" onclick="checkNo(id)">
		  			  <%= radio_button_tag(:energetic, "-1", false, required: 'required') %>
		  	</label>
		  	<label for="energetic_0" id="energetic-label-2" class="check-maybe" onclick="checkMaybe(id)">
		  		<%= radio_button_tag(:energetic, "0") %>
		  	</label>
		  	<label for="energetic_1" id="energetic-label-3" class="check-yes" onclick="checkYes(id)">
		  		<%= radio_button_tag(:energetic, "1") %>
		  	</label><span class="label-yes">YES</span>
		  </div>

		  <div class="each-question">
		  	<div class="question-content">People often tell me secrets.</div>
		  	<span class="label-no">NO</span>
		  	<label for="brave_-1" id="brave-label-1" class="check-no" onclick="checkNo(id)">
		  		<%= radio_button_tag(:brave, "-1", false, required: 'required') %>
		  	</label>
		  	<label for="brave_0" id="brave-label-2" class="check-maybe" onclick="checkMaybe(id)">
		  		<%= radio_button_tag(:brave, "0") %>
		  	</label>
		  	<label for="brave_1" id="brave-label-3" class="check-yes" onclick="checkYes(id)">
		  		<%= radio_button_tag(:brave, "1") %>
		  	</label><span class="label-yes">YES</span>
		  </div>

		  <div class="each-question">
		  	<div class="question-content">I would eat pizza if all of my friends want.</div>
		  	<span class="label-no">NO</span>
		  	<label for="gentle_-1" id="gentle-label-1" class="check-no" onclick="checkNo(id)">
		  		<%= radio_button_tag(:gentle, "-1", false, required: 'required') %>
		  	</label>
		  	<label for="gentle_0" id="gentle-label-2" class="check-maybe" onclick="checkMaybe(id)">
		  		<%= radio_button_tag(:gentle, "0") %>
		  	</label>
		  	<label for="gentle_1" id="gentle-label-3" class="check-yes" onclick="checkYes(id)">
		  		<%= radio_button_tag(:gentle, "1") %>
		  	</label><span class="label-yes">YES</span>
		  </div>

		  <div class="each-question">
		  	<div class="question-content">I have a hobby that I have been doing for a long time.</div>
		  	<span class="label-no">NO</span>
		  	<label for="patient_-1" id="patient-label-1" class="check-no" onclick="checkNo(id)">
		  		 	 <%= radio_button_tag(:patient, "-1", false, required: 'required') %>
		  	</label>
		  	<label for="patient_0" id="patient-label-2" class="check-maybe" onclick="checkMaybe(id)">
		  		<%= radio_button_tag(:patient, "0") %>
		  	</label>
		  	<label for="patient_1" id="patient-label-3" class="check-yes" onclick="checkYes(id)">
		  		<%= radio_button_tag(:patient, "1") %>
		  	</label><span class="label-yes">YES</span>
		  </div>

		  <div class="each-question">
		  	<div class="question-content">I'm a person who doesn't change my mind regardless of what other people think.</div>
		  	<span class="label-no">NO</span>
		  	<label for="stubborn_-1" id="stubborn-label-1" class="check-no" onclick="checkNo(id)">
		  		<%= radio_button_tag(:stubborn, "-1", false, required: 'required') %>
		  	</label>
		  	<label for="stubborn_0" id="stubborn-label-2" class="check-maybe" onclick="checkMaybe(id)">
		  		<%= radio_button_tag(:stubborn, "0") %>
		  	</label>
		  	<label for="stubborn_1" id="stubborn-label-3" class="check-yes" onclick="checkYes(id)">
		  		<%= radio_button_tag(:stubborn, "1") %>
		  	</label><span class="label-yes">YES</span>
		  </div>


		  <div class="each-question">
		  	<div class="question-content">Love ACTION MOVIES!</div><span class="label-no">NO</span>
			<label for="active_-1" id="active-label-1" class="check-no" onclick="checkNo(id)">
		 	 <%= radio_button_tag(:active, "-1", false, required: 'required') %>
		 	</label>
		 	<label for="active_0" id="active-label-2" class="check-maybe" onclick="checkMaybe(id)">
		 		<%= radio_button_tag(:active, "0") %>
		 	</label>
		 	<label for="active_1" id="active-label-3" class="check-yes" onclick="checkYes(id)">
		 		<%= radio_button_tag(:active, "1") %>
		 	</label><span class="label-yes">YES</span>
		  </div>


		  <div class="each-question">
		  	<div class="question-content">I can use a cell phone for 2 years without a breakdown.</div><span class="label-no">NO</span>
		  	<label for="cautious_-1" id="cautious-label-1" class="check-no" onclick="checkNo(id)">
		  		<%= radio_button_tag(:cautious, "-1", false, required: 'required') %>
		  	</label>
		  	<label for="cautious_0" id="cautious-label-2" class="check-maybe" onclick="checkMaybe(id)">
		  		<%= radio_button_tag(:cautious, "0") %>
		  	</label>
		  	<label for="cautious_1" id="cautious-label-3" class="check-yes" onclick="checkYes(id)">
		  		<%= radio_button_tag(:cautious, "1") %>
		  	</label><span class="label-yes">YES</span>
		  </div>


		  <div class="each-question">
		  	<div class="question-content">I like books more than exercise.</div><span class="label-no">NO</span>
		  	<label for="quiet_-1" id="quiet-label-1" class="check-no" onclick="checkNo(id)">
		  			  <%= radio_button_tag(:quiet, "-1", false, required: 'required') %>
		  	</label>
		  	<label for="quiet_0" id="quiet-label-2"  class="check-maybe" onclick="checkMaybe(id)">
		  		<%= radio_button_tag(:quiet, "0") %>
		  	</label>
		  	<label for="quiet_1" id="quiet-label-3"  class="check-yes" onclick="checkYes(id)">
		  		<%= radio_button_tag(:quiet, "1") %>
		  	</label><span class="label-yes">YES</span>
		  </div>


		  <div class="each-question">
		  	<div class="question-content">Without my cell phone, I hate calculating tips.</div><span class="label-no">NO</span>
		  	<label for="straightforward_-1" id="straightforward-label-1" class="check-no" onclick="checkNo(id)">
		  			  <%= radio_button_tag(:straightforward, "-1", false, required: 'required') %>
		  	</label>
		  	<label for="straightforward_0" id="straightforward-label-2" class="check-maybe" onclick="checkMaybe(id)">
		  		<%= radio_button_tag(:straightforward, "0") %>
		  	</label>
		  	<label for="straightforward_1" id="straightforward-label-3" class="check-yes" onclick="checkYes(id)">
		  		<%= radio_button_tag(:straightforward, "1") %>
		  	</label><span class="label-yes">YES</span>
		  </div>


		  <div class="each-question">
		  	<div class="question-content">I like watching movies alone rather than together with others.</div><span class="label-no">NO</span>
		  	<label for="independent_-1" id="independent-label-1" class="check-no" onclick="checkNo(id)">
		  		<%= radio_button_tag(:independent, "-1", false, required: 'required') %>
		  	</label>
		  	<label for="independent_0" id="independent-label-2" class="check-maybe" onclick="checkMaybe(id)">
		  		<%= radio_button_tag(:independent, "0") %>
		  	</label>
		  	<label for="independent_1" id="independent-label-3" class="check-yes" onclick="checkYes(id)">
		  		<%= radio_button_tag(:independent, "1") %>
		  	</label><span class="label-yes">YES</span>
		  </div>

		  <%= submit_tag 'Find The Dog', name: nil, id: "submit", class:"btn btn__start btn__find" %>
		<% end %>
	</section>
</main>
<footer>
	<div class="container">
		<div class="row">
			<div class="col-sm-2">
				<%= link_to "Proj.Binoo", about_path, class:"result-link" %>
			</div>
			<div class="col-sm-2 col-sm-offset-8 text-right">
				<%= link_to "May.2018", root_path, class: "result-link" %>
			</div>
		</div>
	</div>
</footer>

app/views/find_the_dog/result.html.erb
<% provide(:title, @result.name + " | Binoo") %>
<% provide(:description, "You are " + @result.name + " !!! " + @result.description) %>
<% provide(:image, request.base_url + asset_path(@result.picture)) %>
<main>
	<section class="result-page">
		<div class="container">
			<div class="row text-center">
				<div class="flex-container">
					<div class="col-lg-6 col-md-10">
						<%= image_tag @result.picture, class: "img-circle result-img img-responsive center-block", alt: "logo" %>
						<h2 class="result-title">You are a <span class="result-dog"><%= @result.name %></span> !!!</h2>
						<p class="result-description center-block">
							<%= @result.description %>(source <%= link_to "wikipedia", "https://en.wikipedia.org/wiki/"+ @result.name, class:"result-link", target:"_blank" %>)<br>
								It seems like <%= @result.name %> can be an awesome friend for you. Why don't you meet your new best friend
							<%= link_to "here", "https://www.google.com/search?q=#{@result.name}&source=lnms&tbm=isch", class:"result-link", target:"_blank" %>?
						</p>
						<div><%= link_to "share", "http://www.facebook.com/sharer/sharer.php?u=#{request.original_url}", class:"btn__start", target:"_blank" %>
							<%= link_to "restart", root_path, class:"btn__start" %></div>

					</div>
				</div>
			</div>
		</div>
	</section>
</main>
<footer>
	<div class="container">
		<div class="row">
			<div class="col-sm-1">
				<%= link_to "Proj.Binoo", about_path, class:"result-link" %>
			</div>
			<div class="col-sm-3 col-sm-offset-8 text-right">
				<a href="https://www.google.com/search?q=animal+shelter+near+me" class="result-link" target="_blank"> Don't buy, <span class="result-bold">Adopt</span>. &#x1F436; </a>
			</div>
		</div>
	</div>
</footer>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
    </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield :title %></title>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-119749020-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-119749020-1');
    </script>

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag 'favicon.png' %>
    <%= favicon_link_tag 'favicon.png', rel: 'apple-touch-icon', type: 'image/png' %>
    <%= render 'layouts/shim' %>
    <link href="https://fonts.googleapis.com/css?family=Lato|Roboto|Sunflower" rel="stylesheet">
    <link rel="stylesheet" href="https://opensource.keycdn.com/fontawesome/4.7.0/font-awesome.min.css" integrity="sha384-dNpIIXE8U05kAbPhy3G1cz+yZmTzA6CY8Vg/u2L9xRnHjJiAK76m2BIEaSEV+/aU" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta name="description" content="<%= yield :description %>">
    <meta property="og:type" content="website">
    <meta property="og:title" content="<%= yield :title %>">
    <meta property="og:description" content="<%= yield :description %>">
    <meta property="og:url" content="<%= request.original_url %>">
    <meta property="og:image" content="<%= yield :image %>">
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>